---

- name: Remove Database volume directory
  become: yes
  file:
    path: "{{ dojot_volume_directory }}/{{item.path}}"
    state: absent
  loop:
    - { path: 'influxdb' }
    - { path: 'influxdb-chronograf' }