---
- name: Delete dojot PV's (Persistent Volume)
  k8s:
    api_version: v1
    kind: PersistentVolume
    name: "{{ item }}"
    state: absent
  with_items:
    - "pv-certificate-acl"
    - "pv-influxdb"
    - "pv-influxdb-chronograf"
    - "pv-kafka"
    - "pv-kafka-ws"
    - "pv-keycloak-init"
    - "pv-keycloak"
    - "pv-kong"
    - "pv-kong-audit"
    - "pv-minio-files"
    - "pv-mongo"
    - "pv-postgres"
    - "pv-x509-ejbca"
    - "pv-x509-identity-mgmt"
    - "pv-zk-data"
    - "pv-zk-log"
    - "pv-consul-server"
    - "pv-telemetria-grafana"

- name: Delete Credencial Vault
  file:
    path: "{{ ansible_facts.user_dir }}/{{item.file}}"
    state: absent
  loop:
    - { file: ".cluster-keys.yaml" }
    - { file: "shard1" }
    - { file: "shard2" }
    - { file: "shard3" }
  when: optional['vault']

- name: Delete secrets directory
  ignore_errors: true
  local_action: command rm -rf {{ playbook_dir }}/inventories/secrets
