- name:  dojot - Kafka WS
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'kafka_ws_deployment.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'kafka_ws_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'kafka_ws_redis_statefulset.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'kafka_ws_redis_service.yaml.j2') | from_yaml }}"

- name: dojot - Kafka WS Persistent Volume Claim
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'kafka_ws_pvc.yaml.j2') | from_yaml }}"
