## This role is responsible for deploying Kafka for dojot

- name: dojot - Secrets Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'dojot_secrets.yaml.j2') | from_yaml }}"
## Uncomment the line bellow for debug secrets
#  - "{{ lookup('template', 'secret_check_pod.yaml.j2') | from_yaml }}"
