---

- name: install | add repository from PPA and install its signing key
  become: yes
  apt_repository:
    repo: "ppa:vbernat/haproxy-{{ haproxy_version }}"
    update_cache: true

- name: install | dependencies
  become: yes
  apt:
    name: "haproxy"
    state: "latest"

- name: configuration | update file
  become: yes
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0640
    validate: 'haproxy -f %s -c'
  notify: restart haproxy