## This role is responsible for deploying the GUI V2 Service for dojot

- name: dojot - GUI V2 Objects
  when: dojot_guiv2_enabled
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'gui_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'gui_deployment.yaml.j2') | from_yaml }}"
