# Set the version of the postgres container to be used
dojot_psql_version: 9.5.21-alpine

# Define credentials for the postgres super user
dojot_psql_super_user: postgres
dojot_psql_super_passwd: "{{ lookup('file', '{{ playbook_dir }}/inventories/secrets//.POSTGRES_PASSWORD') }}"

dojot_psql_kong_user: kong
dojot_psql_kong_passwd: "{{ lookup('file', '{{ playbook_dir }}/inventories/secrets//.KONG_PASSWORD') }}"
dojot_psql_kong_db: kong

dojot_psql_ejbca_user: ejbca
dojot_psql_ejbca_passwd: ejbca
dojot_psql_ejbca_db: ejbca

dojot_psql_auth_user: auth
dojot_psql_auth_passwd: auth

dojot_psql_devm_user: devm
dojot_psql_devm_passwd: devm

# Name of the default db created by postgres
dojot_psql_default_db: postgres

# Port to be used with the postgreSQL DB
dojot_psql_port: 5432

dojot_psql_volume_size: 2Gi
