## This role is responsible for deploying Kafka for dojot

## This role is responsible for deploying postgreSQL for dojot
- name: Keycloak | Secret Vault
  when: optional['vault']
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'keycloak_external_secrets.yaml') | from_yaml }}"

- name: Keycloak | Secret Kubernetes
  when: not optional['vault']
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'keycloak_secret.yaml.j2') | from_yaml }}"


- name: dojot - Keycloak Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'keycloak_statefulset.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'keycloak_init_job.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'keycloak_proxy_deployment.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'keycloak_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'keycloak_proxy_service.yaml.j2') | from_yaml }}"

- name: dojot - Keycloak Init Persistent Volume Claim
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'keycloak_init_pvc.yaml.j2') | from_yaml }}"