# The group k8s-endpoint refer to the nodes that have access to the kubernetes api
# Its is possible to run from localhost accessing a remote node by defining a kubeconfig file
- hosts: dojot-k8s[0]
  gather_facts: true
  any_errors_fatal: true
  tags:
  - bootstrap
  - vernemq
  - mosca
  - lwm2m
  - 100k
  roles:
    - role: k8s-api-bootstrap

# Create dojot base for the deployment
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags:
  - bootstrap
  - vernemq
  - mosca
  - lwm2m
  - 100k
  roles:
    - role: dojot-basic

# Minio
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags:
  - minio
  - vernemq
  - mosca
  - lwm2m
  
  roles:
    - role: minio

# Metrics (Prometheus, Grafana, Node Exporter)
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags:
  - metrics
  - vernemq
  - mosca
  - lwm2m
  - 100k
  roles:
    - role: metrics

# Deploy ZK to the environment
# TODO: Add possibility of using an external zk by setting config variables
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags:
  - zookeeper
  - kafka
  - vernemq
  - mosca
  - lwm2m
  - 100k
  roles:
    - role: zookeeper
      when: not dojot_zk_use_external


# Deploy postgreSQL to the environment
# TODO: Add possibility of using an external postgres by setting DB config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags:
  - postgresql
  - vernemq
  - mosca
  - lwm2m
  - 100k
  roles:
    - role: databases/postgresql

# Deploy mongoDB to the environment
# TODO: Add possibility of using an external mongodb by setting DB config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags:
  - mongodb
  - vernemq
  - mosca
  - lwm2m
  - 100k
  roles:
    - role: databases/mongodb

# Deploy Kafka to the environment
# TODO: Add possibility of using an external kafka by setting config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags:
  - kafka
  - vernemq
  - mosca
  - lwm2m
  - 100k
  roles:
    - role: kafka

# Deploy verneMq to the environment
# TODO: Add possibility of using an external verneMQ by setting config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags:
  - vernemq
  - 100k
  roles:
    - role: vernemq

# Deploy RabbitMQ to the environment
# TODO: Add possibility of using an external rabbit by setting config variables
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags:
  - rabbitmq
  - vernemq      
  - mosca
  - lwm2m
  roles:
    - role: rabbitmq


# Deploy Dojot Components to the Environment
# Deploy the dojot services
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: dojot-components
  roles:

    - role: image-manager
      tags:      
      - vernemq
      - mosca
      - lwm2m

    - role: apigw
      tags:
      - vernemq
      - mosca
      - lwm2m
      - 100k

    - role: auth
      tags:
      - vernemq
      - mosca
      - lwm2m
      - 100k 

    - role: backstage
      tags:
      - vernemq      
      - mosca
      - lwm2m

    - role: data-broker
      tags:
      - vernemq      
      - mosca
      - lwm2m
      - 100k 

    - role: device-manager
      tags:
      - vernemq      
      - mosca
      - lwm2m
      
    - role: history
      tags: 
      - vernemq      
      - mosca
      - lwm2m
      
    - role: persister
      tags:
      - vernemq      
      - mosca
      - lwm2m
      
    - role: gui
      tags:
      - vernemq      
      - mosca
      - lwm2m
      
    - role: iotagent-mosca
      tags:
      - never
      - mosca

    - role: iotagent-lwm2m
      tags:
      - never
      - lwm2m 
      
    - role: flowbroker
      tags:
      - vernemq      
      - mosca
      - lwm2m
     
    - role: data-manager
      tags:
      - vernemq      
      - mosca
      - lwm2m
      
    - role: cron
      tags:
      - vernemq      
      - mosca
      - lwm2m
      
    - role: v2k-bridge
      tags:
      - vernemq
      - 100k

    - role: k2v-bridge
      tags:
      - vernemq
      - 100k

    - role: kafka2ftp
      tags:
      - vernemq      
      - mosca
      - lwm2m

    - role: kafka-loopback
      tags:
      - never
      - 100k

    - role: kafka-ws
      tags:
      - vernemq      
      - mosca
      - lwm2m
      - 100k

    - role: x509-identity-mgmt
      tags:
      - vernemq      
      - mosca
      - lwm2m
      - 100k