---
# The group k8s-endpoint refer to the nodes that have access to the kubernetes api
# Its is possible to run from localhost accessing a remote node by defining a kubeconfig file
- hosts: dojot-k8s[0]
  gather_facts: true
  any_errors_fatal: true
  tags: [dojot-bootstrap, 100k]
  roles:
    - role: k8s-api-bootstrap

# Create dojot base for the deployment
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-bootstrap, 100k]
  roles:
    - role: dojot-basic

# Deploy ZK to the environment
# TODO: Add possibility of using an external zk by setting config variables
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: dojot-minio
  roles:
    - role: minio

#Metrics
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [metrics, 100k]
  roles:
    - role: metrics

# Deploy ZK to the environment
# TODO: Add possibility of using an external zk by setting config variables
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-zk, dojot-kafka, 100k]
  roles:
    - role: zookeeper
      when: not dojot_zk_use_external


# Deploy postgreSQL to the environment
# TODO: Add possibility of using an external postgres by setting DB config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-psql, 100k]
  roles:
    - role: databases/postgresql

# Deploy postgreSQL to the environment
# TODO: Add possibility of using an external postgres by setting DB config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-psql-ejbca, 100k]
  roles:
    - role: databases/postgres-ejbca

# Deploy mongoDB to the environment
# TODO: Add possibility of using an external mongodb by setting DB config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: dojot-mongodb
  roles:
    - role: databases/mongodb

# Deploy Kafka to the environment
# TODO: Add possibility of using an external kafka by setting config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-kafka, 100k]
  roles:
    - role: kafka

# Deploy verneMq to the environment
# TODO: Add possibility of using an external verneMQ by setting config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-vernemq, 100k]
  roles:
    - role: vernemq

# Deploy RabbitMQ to the environment
# TODO: Add possibility of using an external rabbit by setting config variables
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-rabbitmq]
  roles:
    - role: rabbitmq


# Deploy Dojot Components to the Environment
# Deploy the dojot services
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: dojot-components
  roles:
    - role: image-manager
    - role: apigw
      tags: 100k
    - role: auth
      tags: 100k
    - role: backstage
    - role: data-broker
      tags: 100k
    - role: ejbca-node
      tags: 100k
    - role: device-manager
    - role: history
    - role: persister
    - role: gui
    - role: iotagent-mosca
      tags: never
    - role: iotagent-lwm2m
    - role: flowbroker
    - role: data-manager
    - role: cron
    - role: v2k-bridge
      tags: 100k
    - role: k2v-bridge
      tags: 100k
    - role: kafka2ftp
    - role: kafka-ws
    - role: kafka-loopback
      tags: [ never, 100k ]
