# The group k8s-endpoint refer to the nodes that have access to the Kubernetes API
# It is possible to run from localhost accessing a remote node by defining a kubeconfig file
- hosts: dojot-k8s[0]
  gather_facts: true
  any_errors_fatal: true
  tags: [dojot-bootstrap, 100k]
  roles:
    - role: k8s-api-bootstrap

# Create dojot base for the deployment
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-bootstrap, 100k]
  roles:
    - role: dojot-basic

# NGINX Ingress Controller and Resources
- hosts: dojot-k8s[0]
  gather_facts: true
  any_errors_fatal: true
  tags: [ingress, 100k]
  roles:
    - role: nginx-ingress

# Minio
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-minio]
  roles:
    - role: minio

# Metrics (Prometheus, Grafana, Node Exporter)
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [metrics, 100k]
  roles:
    - role: metrics

# Deploy Zookeeper to the environment
# TODO: Add possibility of using an external Zookeeper by setting config variables
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-zk, dojot-kafka, 100k]
  roles:
    - role: zookeeper
      when: not dojot_zk_use_external

# Deploy PostgreSQL to the environment
# TODO: Add possibility of using an external PostgreSQL by setting DB config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-psql, 100k]
  roles:
    - role: databases/postgresql

# Deploy MongoDB to the environment
# TODO: Add possibility of using an external MongoDB by setting DB config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-mongodb, 100k]
  roles:
    - role: databases/mongodb

# Deploy Kafka to the environment
# TODO: Add possibility of using an external Kafka by setting config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-kafka, 100k]
  roles:
    - role: kafka

# Deploy VerneMQ to the environment
# TODO: Add possibility of using an external VerneMQ by setting config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-vernemq, 100k]
  roles:
    - role: vernemq

# Deploy RabbitMQ to the environment
# TODO: Add possibility of using an external RabbitMQ by setting config variables
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: [dojot-rabbitmq]
  roles:
    - role: rabbitmq


# Deploy Dojot Components to the Environment
# Deploy the dojot services
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  tags: dojot-components
  roles:
    - role: image-manager
    - role: apigw
      tags: [100k]
    - role: auth
      tags: [100k]
    - role: backstage
    - role: data-broker
      tags: [100k]
    - role: device-manager
    - role: history
    - role: persister
    - role: gui
    - role: iotagent-mosca
      tags: [never]
    - role: iotagent-lwm2m
    - role: flowbroker
    - role: data-manager
    - role: cron
    - role: v2k-bridge
      tags: [100k]
    - role: k2v-bridge
      tags: [100k]
    - role: kafka2ftp
    - role: kafka-loopback
      tags: [never, 100k]
    - role: kafka-ws
      tags: [100k]
    - role: x509-identity-mgmt
      tags: [100k]
