---
- hosts: dojot_nodes
  gather_facts: true
  any_errors_fatal: true
  tags:
    - volumes
  roles:
    - role: volumes/kong
      tags:
        - kong
    - role: volumes/minio
      tags:
        - minio
    - role: volumes/minio-files
      tags:
        - minio-files
    - role: volumes/mongodb
      tags:
        - mongodb
    - role: volumes/postgres
      tags:
        - postgresql
    - role: volumes/kafka-ws
      tags:
        - kafka-ws

- hosts: kafka_nodes
  gather_facts: true
  any_errors_fatal: true
  tags:
    - volumes
  roles:
    - role: volumes/kafka
      tags:
        - kafka
    - role: volumes/zookeeper
      tags:
        - zookeeper

- hosts: x509_nodes
  gather_facts: true
  any_errors_fatal: true
  tags:
    - volumes
  roles:
    - role: volumes/x509-ejbca
      tags:
        - x509-ejbca
    - role: volumes/x509-identity-mgmt
      tags:
        - x509-identity-mgmt
    - role: volumes/certificate-acl
      tags:
        - certificate-acl

- hosts: database_nodes
  gather_facts: true
  any_errors_fatal: true
  tags:
    - volumes
  roles:
    - role: volumes/influxdb
      tags:
        - influxdb
    - role: volumes/influxdb-chronograf
      tags:
        - influxdb-chronograf

- hosts: master_nodes
  gather_facts: true
  any_errors_fatal: true
  tags:
    - volumes
  roles:
    - role: volumes/storageclass
      tags:
        - storageclass
    - role: volumes/kong
      tags:
        - kong
    - role: volumes/minio
      tags:
        - minio
    - role: volumes/minio-files
      tags:
        - minio-files
    - role: volumes/mongodb
      tags:
        - mongodb
    - role: volumes/postgres
      tags:
        - postgresql
    - role: volumes/kafka-ws
      tags:
        - kafka-ws
    - role: volumes/kafka
      tags:
        - kafka
    - role: volumes/zookeeper
      tags:
        - zookeeper
    - role: volumes/x509-ejbca
      tags:
        - x509-ejbca
    - role: volumes/x509-identity-mgmt
      tags:
        - x509-identity-mgmt
    - role: volumes/influxdb
      tags:
        - influxdb
    - role: volumes/influxdb-chronograf
      tags:
        - influxdb-chronograf
    - role: volumes/certificate-acl
      tags:
        - certificate-acl