## This role is responsible for deploying HTTP Agent for dojot

- name: dojot - http_agent_basic Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'http_agent_basic_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'http_agent_basic_deployment.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'http_agent_basic_redis_statefulset.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'http_agent_basic_redis_service.yaml.j2') | from_yaml }}"