---

- name: Remove Kafka volume directory
  become: yes
  file:
    path: "{{ dojot_volume_directory }}/{{item.path}}"
    state: absent
  loop:
    - { path: 'kafka' }
    - { path: 'kafka_ws' }
    - { path: 'zookeeper' }