apiVersion: v1
kind: PersistentVolume
metadata:
  name: x509-identity-pv
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: dojot
    name: x509-identity-pvc
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/x509
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - verne-kafka