---

- name: Remove volume directory
  become: yes
  file:
    path: "{{ dojot_volume_directory }}/{{item.path}}"
    state: absent
  loop:
    - { path: 'prometheus' }
    - { path: 'grafana' }
    - { path: 'loki' }
  when: (dojot_storage_class_name == "local-storage")