---
- name: Volume | Loki  | Create directory if it does not exists
  become: true
  ansible.builtin.file:
    path: "{{ dojot_volume_directory }}/loki"
    state: directory
    owner: root
    group: root
    mode: "2775"
  when: (dojot_storage_class_name == "local-storage") and
        ('monitoring_nodes' in group_names)

- name: Volume | Loki | Create persistent volume
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
    - "{{ lookup('template', 'loki.yaml.j2') | from_yaml }}"
  when: (dojot_storage_class_name == "local-storage") and
        ('master_nodes' in group_names)
