# This files has the default values for dojot API Gateway variables

dojot_internal_http_port: 8000
dojot_internal_https_port: 8443
dojot_internal_api_config_port: 8001

dojot_apigw_version: "{{ dojot_backend_version }}"
dojot_apigw_volume_size: 5Mi

dojot_psql_kong_user: kong
dojot_psql_kong_passwd: "{{ lookup('file', '{{ playbook_dir }}/inventories/secrets/.KONG_PASSWORD') }}"
dojot_psql_kong_db: kong
