apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-kong
  labels:
    type: local
    app: dojot
    name: kong
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/kong
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - k8s17-worker
