apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-kafka-ws
  labels:
    type: local
    app: dojot
    name: kafka-ws
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/kafka_ws
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: dojot.components/group
          operator: In
          values:
          - dojot
