apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-postgres
  labels:
    type: local
    app: dojot
    db: postgres
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: dojot.components/dojot
          operator: In
          values:
          - true
