apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-prometheus
  labels:
    type: local
    db: prometheus
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: dojot.components/group
          operator: In
          values:
          - dojot
