apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-x509-ejbca-tls
  labels:
    type: local
    app: dojot
    name: x509-ejbca-tls
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/ejbca-tls
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: dojot.components/group
          operator: In
          values:
          - x509