apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-x509-identity-mgmt
  labels:
    type: local
    app: dojot
    name: x509-identity-mgmt
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/ejbca
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - k8s17-worker
