apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-zk-data
  labels:
    type: local
    app: dojot
    name: zookeeper-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/zookeeper/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s17-worker
