## This role is responsible for deploying Kong for dojot

- name: dojot - FILE-MGMT Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 2
  delay: 10
  loop:
  - "{{ lookup('template', 'file-mgmt_createbucket_job.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'file-mgmt_deployment.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'file-mgmt_service.yaml.j2') | from_yaml }}"