---

- name: containerd status
  become: yes
  service: name=containerd state=started

- name: systemd daemon reload
  become: yes
  command: systemctl daemon-reload

- name: modprobe overlay
  become: yes
  command: modprobe overlay

- name: modprobe br_netfilter
  become: yes
  command: modprobe br_netfilter

- name: sysctl reload
  become: yes
  command: sysctl --system

- name: containerd restart
  become: yes
  command: systemctl restart containerd