## This role is responsible for deploying the InfluxDB Retriever Service for dojot

- name: dojot - InfluxDB Retriever Objects
  when: optional['influxdb_retriever'] and optional['influxdb']
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'influxdb_retriever_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'influxdb_retriever_deployment.yaml.j2') | from_yaml }}"
