- name: Create StorageClass
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'storageclass.yaml.j2') | from_yaml }}"
  when: (dojot_storage_class_name == "local-storage") and
        ('master_nodes' in group_names)
