---
- name: Create StorageClass LOCAL
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'local-storageclass.yaml.j2') | from_yaml }}"
  when: ('master_nodes' in group_names)

- name: Create StorageClass NFS
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'nfs-storageclass.yaml.j2') | from_yaml }}"
  when: (dojot_storage_class_name == "nfs") and
        ('master_nodes' in group_names)