## This role is responsible for deploying the Persister Service for dojot

- name: dojot - InfluxDB Chronograf deployment
  when: optional['influxdb_chronograf'] and optional['influxdb']
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'influxdb_chronograf_statefulset.yaml.j2') | from_yaml }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10