dojot_influxdb_version: v2.0.2
dojot_influxdb_port: 8086
dojot_influxdb_user: dojot
dojot_influxdb_token: dojot@token_default
dojot_influxdb_passwd: dojot@password
dojot_influxdb_organization_name: admin
dojot_influxdb_bucket: devices
# this retention is only for the organization `dojot_influxdb_organization_name` created when starting influxdb.
# For other retentions it is necessary to use an environment variable in the influxdb-storer.
# It is considered only the first time that InfluxDB is started.
# Valid units are nanoseconds (ns), microseconds (us or µs), milliseconds (ms), seconds (s), minutes (m), hours (h), days (d),  weeks (w) and 0 is infinite retention
dojot_influxdb_retention: 7d
dojot_influxdb_volume_size: 2Gi
