---
all:
  hosts:
    localhost:
        ansible_connection: local
        ansible_python.version.major: 3
        ansible_python_interpreter: /usr/bin/python3
    # If you are using ansible in a control node (outside of master) you should uncomment
    # master_host declaration (lines 11...14) and then change the lines 34 and 40
    # pointing to "master_host"
    # master_host:
    #     ansible_host: MASTER_HOST_ADDRESS #change to the host of master node on k8s
    #     ansible_python.version.major: 3
    #     ansible_python_interpreter: /usr/bin/python3
    worker_host:
        ansible_host: WORKER_HOST_ADDRESS #change to the host of worker node on k8s
        ansible_python_interpreter: /usr/bin/python3
    nginx:
        ansible_host: NGINX_HOST_ADDRESS #change to the host of NGINX
        ansible_python_interpreter: /usr/bin/python3
    haproxy:
        ansible_host: HAPROXY_HOST_ADDRESS #change to the host of NGINX
        ansible_python_interpreter: /usr/bin/python3
    nfs_host:
        ansible_host: NFS-SERVER_HOST_ADDRESS #change to the host of NFS Server
    k3s_host:
        ansible_host: K3S_HOST_ADDRESS #change to the host of K3S Server
        ansible_python_interpreter: /usr/bin/python3

  children:
    #host where dojot will be deployed
    dojot-k8s:
      hosts:
        localhost:
    #hosts that will be part of the k8s cluster
    k8s-nodes:
      children:
        master_nodes:
          hosts:
            localhost:
        worker_nodes:
          hosts:
            worker_host:
    k3s-nodes:
      hosts:
        k3s_host:
    #hosts where volumes will be mapped
    volume-nodes:
      children:
        dojot_nodes:
          hosts:
            worker_host: #host for dojot related services volumes (apigw; influxdb; kafka_ws; minio; mongodb; postgres; prometheus;)
            # nfs_host: #host for dojot related services volumes. If you are using NFS volume with NFS SERVER you should uncomment this line and comment the line above.
        kafka_nodes:
          hosts:
            worker_host: #host for kafka related services volumes (kafka; zookeeper;)
            # nfs_host: #host for dojot related services volumes. If you are using NFS volume with NFS SERVER you should uncomment this line and comment the line above.
        x509_nodes:
          hosts:
            worker_host: #host for x509 related services volumes (x509;)
            # nfs_host: #host for dojot related services volumes. If you are using NFS volume with NFS SERVER you should uncomment this line and comment the line above.

    apigw_nodes:
      hosts:
        APIGW_HOST_ADDRESS: #change to the host of API GW worker node on k8s
    mqtt_nodes:
      hosts:
        MQTT_HOST_ADDRESS: #change to the host of MQTT worker node on k8s
    http_agent_nodes:
      hosts:
        HTTP_AGENT_HOST_ADDRESS: #change to the host of HTTP Agent worker node on k8s
    lwm2m_nodes:
      hosts:
        LWM2M_HOST_ADDRESS: #change to the host of LWM2M worker node on k8s
    metrics_nodes:
      hosts:
        METRICS_HOST_ADDRESS: #change to the host of Metrics worker node on k8s

