---
all:
  hosts:
    localhost:
        ansible_connection: local
        ansible_python.version.major: 3
    worker_host:
        ansible_host: WORKER_HOST_ADDRESS #change to the host of worker node on k8s
    nginx:
        ansible_host: NGINX_HOST_ADDRESS #change to the host of NGINX
    haproxy:
        ansible_host: HAPROXY_HOST_ADDRESS #change to the host of NGINX
  children:
    #host where dojot will be deployed
    dojot-k8s:
      hosts:
        localhost:
    #hosts that will be part of the k8s cluster
    k8s-nodes:
      children:
        master_nodes:
          hosts:
            localhost:
        worker_nodes:
          hosts:
            worker_host:
    #hosts where volumes will be mapped
    volume-nodes:
      children:
        dojot_nodes:
          hosts:
            worker_host: #host for dojot related services volumes (apigw; influxdb; kafka_ws; minio; mongodb; postgres; prometheus;)
        kafka_nodes:
          hosts:
            worker_host: #host for kafka related services volumes (kafka; zookeeper;)
        x509_nodes:
          hosts:
            worker_host: #host for x509 related services volumes (x509;)

    apigw_nodes:
      hosts:
        APIGW_HOST_ADDRESS: #change to the host of API GW worker node on k8s
    mqtt_nodes:
      hosts:
        MQTT_HOST_ADDRESS: #change to the host of MQTT worker node on k8s
    lwm2m_nodes:
      hosts:
        LWM2M_HOST_ADDRESS: #change to the host of LWM2M worker node on k8s
    metrics_nodes:
      hosts:
        METRICS_HOST_ADDRESS: #change to the host of Metrics worker node on k8s

