---

- name: Create influxdb chronograf directory if it does not exists
  become: true
  file:
    path: "{{ dojot_volume_directory }}/influxdb-chronograf"
    state: directory
  when: (dojot_storage_class_name == "local-storage") and
        ('database_nodes' in group_names)

- name: Create influxdb chronograf volume
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'influxdb-chronograf.yaml.j2') | from_yaml }}"
  when: (dojot_storage_class_name == "local-storage") and
        ('master_nodes' in group_names)