## This role is responsible for deploying the Persister Service for dojot

- name: dojot - InfluxDB Storer deployment
  when: optional['influxdb_storer'] and optional['influxdb']
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'influxdb_storer_deployment.yaml.j2') | from_yaml }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
