---
# roles/metrics/tasks/helm.yml
- name: Metrics | Helm | Create download directory
  file:
    state: directory
    mode: "u=rwx,go=x"
    dest: "{{ dojot_helm_download_dir }}"

- name: Metrics | Helm | Download sha256sum file
  get_url:
    url: "{{ dojot_helm_mirror }}/{{ dojot_helm_redistributable_filename }}.sha256"
    dest: "{{ dojot_helm_download_dir }}/{{ dojot_helm_redistributable_filename }}.sha256"
    force: no
    validate_certs: yes
    mode: "u=rw,go=r"

- name: Metrics | Helm | Read sha256sum file
  slurp:
    src: "{{ dojot_helm_download_dir }}/{{ dojot_helm_redistributable_filename }}.sha256"
  register: helm_sha256sum

- name: Metrics | Helm | Download Helm
  get_url:
    url: "{{ dojot_helm_mirror }}/{{ dojot_helm_redistributable_filename }}"
    dest: "{{ dojot_helm_download_dir }}/{{ dojot_helm_redistributable_filename }}"
    sha256sum: "{{ helm_sha256sum.content | b64decode | trim }}"
    force: no
    validate_certs: yes
    mode: "u=rw,go=r"

- name: Metrics | Helm | Create the Helm installation directory
  become: true
  file:
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=x"
    dest: "{{ dojot_helm_install_dir }}"

- name: Metrics | Helm | Install Helm
  become: true
  unarchive:
    src: "{{ dojot_helm_download_dir }}/{{ dojot_helm_redistributable_filename }}"
    remote_src: yes
    dest: "{{ dojot_helm_install_dir }}"
    extra_opts:
      - "--strip-components=1"
    owner: root
    group: root
    mode: "o-w"
    creates: "{{ dojot_helm_install_dir }}/helm"

- name: Metrics | Helm | Create Helm symlink to OS path
  become: true
  file:
    src: "{{ dojot_helm_install_dir }}/helm"
    dest: "/usr/local/bin/helm"
    state: link
    owner: root
    group: root
    mode: "u=rwx,go=rx"

- name: Metrics | Helm | Install Helm diff plugin for better idempotency
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present
