- name: Add stable chart repo keda
  when: optional['keda']
  kubernetes.core.helm_repository:
    name: kedacore
    repo_url: "https://kedacore.github.io/charts"

- name: Deploy latest version of Keda chart inside keda namespace
  when: optional['keda']
  kubernetes.core.helm:
    name: keda
    chart_ref: kedacore/keda
    release_namespace: keda
    create_namespace: true