---

- name: Create minio-files directory if it does not exists
  become: true
  file:
    path: "{{ dojot_volume_directory }}/minio-files"
    state: directory
  when: ('dojot_nodes' in group_names)

- name: Create minio-files volume
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'minio_files.yaml.j2') | from_yaml }}"
  when: ('master_nodes' in group_names)