apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: dojot-monitoring
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: dojot-monitoring
spec:
  selector:
    app: grafana

  ports:
    - name: http
      port: 3000

  type: NodePort
