---

- name: Create grafana directory if it does not exists
  become: true
  file:
    path: "{{ dojot_volume_directory }}/grafana"
    state: directory
    mode: "2775"
  when: (dojot_storage_class_name == "local-storage") and
        ('monitoring_nodes' in group_names)

- name: Create grafana volume
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'grafana.yaml.j2') | from_yaml }}"
  when: (dojot_storage_class_name == "local-storage") and
        ('master_nodes' in group_names)
