---

- name: Install packages that allow apt to be used over HTTPS
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - python3-pip
    - gnupg2
    - software-properties-common

- name: Add an apt signing key for containerd
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
    state: present

- name: Install containerd
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - containerd.io={{ containerd_version }}
  notify:
    - containerd status

- name: Load Modules for Containerd
  become: yes
  template:
    src: containerd.conf.j2
    dest: /etc/modules-load.d/containerd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - modprobe overlay
    - modprobe br_netfilter

- name: Setup required sysctl params
  become: yes
  template:
    src: 99-kubernetes-cri.conf.j2
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - sysctl reload

- name: Create config dir containerd
  become: yes
  command: "mkdir -p /etc/containerd"

- name: Get defaults from containerd
  become: yes
  command: containerd config default
  changed_when: false
  register: containerd_config_default

- name: Write defaults to config.toml.
  become: yes
  copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_config_default.stdout }}"
  notify: containerd restart

- name: Remove swapfile from /etc/fstab
  become: yes
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  become: yes
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt-key for Kubernetes
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  become: yes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet={{ k8s_version }}
      - kubeadm={{ k8s_version }}
      - kubectl={{ k8s_version }}