---

- name: Install packages that allow apt to be used over HTTPS
  tags:
  - docker
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - python3-pip
    - gnupg2
    - software-properties-common

- name: Add an apt signing key for Docker
  tags:
  - docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  tags:
  - docker
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
    state: present

- name: Install docker and its dependecies
  tags:
  - docker
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce=5:19.03.14~3-0~ubuntu-{{ ansible_facts.lsb.codename }}
    - docker-ce-cli=5:19.03.14~3-0~ubuntu-{{ ansible_facts.lsb.codename }}
    - containerd.io=1.2.10-3
  notify:
    - docker status

- name: Docker daemon settings
  tags:
  - docker
  become: yes
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd daemon reload
    - restart docker

- name: Remove swapfile from /etc/fstab
  become: yes
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  become: yes
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  become: yes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet={{ k8s_version }}
      - kubeadm={{ k8s_version }}
      - kubectl={{ k8s_version }}