apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-consul-client-config
  namespace: {{ dojot_namespace }}
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: consul
    component: client
data:
  client.json: |-
    {
    }
  extra-from-values.json: |-
    {}

  central-config.json: |-
    {
      "enable_central_service_config": true
    }
