apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-consul-client
  namespace: {{ dojot_namespace }}
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: consul
    component: client