# Nodenames of dojot worker nodes that will be labeled
dojot_dojot_nodenames:   # Nodes that will receive the label for the rest of the services
  - eri-worker
# - k8s-worker2-nodename #If you want you can add multiple nodes to receive the same label

dojot_kafka_nodenames:   # Nodes that will receive the label for Kafka, Zookeeper and Kafka Loopback node
  - eri-worker

dojot_x509_nodenames:    # Nodes that will receive the label for x509 node
  - eri-worker

dojot_vernemq_nodenames: # Nodes that will receive the label for VerneMQ, K2V and V2K nodes
  - eri-worker
