- name: Metrics | Alertmanager | Add alertmanager helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Metrics | Alertmanager | Deploy alertmanager chart with values loaded from template
  kubernetes.core.helm:
    chart_ref: prometheus-community/alertmanager
    chart_version: 0.15.0
    release_name: alertmanager
    release_namespace: "{{ dojot_monitoring_namespace }}"
    values: "{{ lookup('template', 'alertmanager/alertmanager-values.yml.j2') | from_yaml }}"