---
- name: Metrics | Monitoring-Stack | Add prometheus helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Metrics | monitoring-stack | Deploy kube-prometheus-stack chart with values loaded from template
  kubernetes.core.helm:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 37.2.0
    release_name: prometheus-stack
    release_namespace: "{{ dojot_monitoring_namespace }}"
    values: "{{ lookup('template', 'monitoring-stack/stack-values.yml.j2') | from_yaml }}"
