- name: Metrics | Prometheus | Add prometheus helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Metrics | Prometheus | Deploy Prometheus chart with values loaded from template
  kubernetes.core.helm:
    chart_ref: prometheus-community/prometheus
    chart_version: 15.5.3
    release_name: prometheus
    release_namespace: "{{ dojot_monitoring_namespace }}"
    create_namespace: true
    values: "{{ lookup('template', 'prometheus/prometheus-values.yml.j2') | from_yaml }}"

- name: Including CRD's
  kubernetes.core.k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  loop:
    - "{{ lookup('template', 'prometheus/monitoring.coreos.com_alertmanagerconfigs.yaml') | from_yaml }}"
    - "{{ lookup('template', 'prometheus/monitoring.coreos.com_alertmanagers.yaml') | from_yaml }}"
    - "{{ lookup('template', 'prometheus/monitoring.coreos.com_podmonitors.yaml') | from_yaml }}"
    - "{{ lookup('template', 'prometheus/monitoring.coreos.com_probes.yaml') | from_yaml }}"
    - "{{ lookup('template', 'prometheus/monitoring.coreos.com_prometheuses.yaml') | from_yaml }}"
    - "{{ lookup('template', 'prometheus/monitoring.coreos.com_prometheusrules.yaml') | from_yaml }}"
    - "{{ lookup('template', 'prometheus/monitoring.coreos.com_servicemonitors.yaml') | from_yaml }}"
    - "{{ lookup('template', 'prometheus/monitoring.coreos.com_thanosrulers.yaml') | from_yaml }}"