- name: Metrics | Prometheus | Add prometheus helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Metrics | Rabbitmq-exporter | Deploy Rabbitmq-exporter chart with values loaded from template
  kubernetes.core.helm:
    name: rabbitmq-exporter
    chart_ref: prometheus-community/prometheus-rabbitmq-exporter
    chart_version: 1.1.0
    release_namespace: "{{ dojot_monitoring_namespace }}"
    values: "{{ lookup('template', 'rabbitmq-exporter/rabbitmq-exporter-values.yml.j2') | from_yaml }}"
