- name: Including Secret
  kubernetes.core.k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  loop:
    - "{{ lookup('template', 'grafana/secrets-grafana.yml.j2') | from_yaml }}"