## This role is responsible for deploying the Persister Service for dojot

- name: dojot - InfluxDB Telegraf Objects
  when: optional['influxdb_telegraf'] and optional['influxdb']
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'influxdb_telegraf_deployment.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'influxdb_telegraf_data_agent_config_map.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'influxdb_telegraf_tenancy_agent_config_map.yaml.j2') | from_yaml }}"