---

- name: Remove Dojot volume directory
  become: yes
  file:
    path: "{{ dojot_volume_directory }}/{{item.path}}"
    state: absent
  loop:
    - { path: 'keycloak' }
    - { path: 'kong' }
    - { path: 'minio-files' }
    - { path: 'mongodb' }
    - { path: 'postgres' }